src/Entity/Comment.php
<?php
/**
 * Comment entity.
 */

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Class Comment.
 */
#[ORM\Entity(repositoryClass: CommentRepository::class)]
#[ORM\Table(name: 'comments')]
class Comment
{
    /**
     * Primary key.
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    /**
     * Content.
     */
    #[ORM\Column(type: 'text')]
    private ?string $content = null;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeImmutable $date;

    /**
     * Photo.
     *
     * @var Photo|null
     */
    #[ORM\ManyToOne(targetEntity: Photo::class, inversedBy: 'comments')]
    private $photo;

    /**
     * Author.
     *
     * @var User|null
     */
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private User $author;

    /**
     * Getter for Id.
     *
     * @return int|null Id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Getter for content.
     *
     * @return string|null Content
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * Setter for content.
     *
     * @param string $content Content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * Getter for date.
     *
     * @return \DateTimeImmutable|null Date
     */
    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    /**
     * Setter for date.
     *
     * @param \DateTimeImmutable $date Date
     */
    public function setDate(\DateTimeImmutable $date): void
    {
        $this->date = $date;
    }

    /**
     * Getter for photo.
     *
     * @return Photo|null Photo
     */
    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    /**
     * Setter for Photo.
     *
     * @param Photo|null $photo Photo entity
     *
     * @return $this
     */
    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Getter for Author.
     *
     * @return User|null author
     */
    public function getAuthor(): ?User
    {
        return $this->author;
    }

    /**
     * Setter for Author.
     *
     * @param User|null $author Author
     *
     * @return $this
     */
    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Entity/User.php
<?php
/**
 * User entity.
 */

namespace App\Entity;

use App\Entity\Enum\UserRole;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class user.
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'users')]
#[ORM\UniqueConstraint(name: 'email_idx', columns: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * Primary key.
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    /**
     * Email.
     */
    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $login;

    /**
     * Roles.
     *
     * @var array<int, string>
     */
    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * Password.
     */
    #[ORM\Column(type: 'string')]
    #[Assert\NotBlank]
    private ?string $password;

    /**
     * Represents the relationship between this object and its associated comments.
     *
     * @var Collection contains the collection of comments associated with this object
     *
     * @ORM\OneToMany(mappedBy="author", targetEntity=Comment::class)
     *
     * @ORM\JoinColumn(nullable=true)
     */
    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    #[ORM\JoinColumn(nullable: true)]
    private Collection $comments;

    /**
     * Represents the author of this object.
     *
     * @var User represents the user who is the author of this object
     */
    private User $author;

    /**
     * Constructs a new instance of this object.
     * Initializes the comments collection as an ArrayCollection.
     */
    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    /**
     * Getter for id.
     *
     * @return int|null Id
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Getter for email.
     *
     * @return string|null Email
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Setter for email.
     *
     * @param string $email Email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Retrieves the login of this object.
     *
     * @return string|null the login of this object, or null if it is not set
     */
    public function getLogin(): ?string
    {
        return $this->login;
    }

    /**
     * Sets the login of this object.
     *
     * @param string|null $login the login to set, or null to unset the login
     */
    public function setLogin(?string $login): void
    {
        $this->login = $login;
    }

    /**
     * A visual identifier that represents this index.html.twig.
     *
     * @return string User identifier
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     *
     * @return string Username
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * Getter for roles.
     *
     * @return array<int, string> Roles
     *
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = UserRole::ROLE_USER->value;

        return array_unique($roles);
    }

    /**
     * Setter for roles.
     *
     * @param array<int, string> $roles Roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Getter for password.
     *
     * @return string|null Password
     *
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Setter for password.
     *
     * @param string $password User password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * Removes sensitive information from the token.
     *
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
    }

    /**
     * Retrieves the comments associated with this object.
     *
     * @return Collection the collection of comments associated with this object
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * Retrieves the author of this object.
     *
     * @return User|null the author of this object, or null if there is no assigned author
     */
    public function getAuthor(): ?User
    {
        return $this->author;
    }

    /**
     * Sets the author of this object.
     *
     * @param User|null $author the author to set, or null if there is no assigned author
     *
     * @return self a reference to itself
     */
    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/Type/CommentType.php
<?php
/**
 * Comment type.
 */

namespace App\Form\Type;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class CommentType.
 */
class CommentType extends AbstractType
{
    /**
     * Builds the form.
     *
     * This method is called for each type in the hierarchy starting from the
     * top most type. Type extensions can further modify the form.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array<string, mixed> $options Form options
     *
     * @see FormTypeExtensionInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'content',
            TextType::class,
            [
                'label' => 'Content',
                'required' => true,
                'attr' => ['max_length' => 6000],
            ]
        );
    }

    /**
     * Configures the options for this type.
     *
     * @param OptionsResolver $resolver The resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(['data_class' => Comment::class]);
    }

    /**
     * Returns the prefix of the template block name for this type.
     *
     * The block prefix defaults to the underscored short class name with
     * the "Type" suffix removed (e.g. "UserProfileType" => "user_profile").
     *
     * @return string The prefix of the template block name
     */
    public function getBlockPrefix(): string
    {
        return 'comment';
    }
}

src/Controller/CommentController.php
<?php
/**
 * Comment controller.
 */

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Photo;
use App\Form\Type\CommentType;
use App\Service\CommentServiceInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Class CommentController.
 */
#[Route('/comment')]
class CommentController extends AbstractController
{
    /**
     * Comment service.
     */
    private CommentServiceInterface $commentService;

    /**
     * Translator.
     */
    private TranslatorInterface $translator;

    /**
     * Constructor.
     */
    public function __construct(CommentServiceInterface $commentService, TranslatorInterface $translator)
    {
        $this->commentService = $commentService;
        $this->translator = $translator;
    }

    /**
     * Index action.
     *
     * @param Request $request HTTP Request
     *
     * @return Response HTTP response
     */
    #[Route(name: 'comment_index', methods: 'GET')]
    public function index(Request $request): Response
    {
        $pagination = $this->commentService->getPaginatedList(
            $request->query->getInt('page', 1)
        );

        return $this->render('comment/index.html.twig', ['pagination' => $pagination]);
    }

    /**
     * Show action.
     *
     * @param Comment $comment Comment
     *
     * @return Response HTTP response
     */
    #[Route(
        '/{id}',
        name: 'comment_show',
        requirements: ['id' => '[1-9]\d*'],
        methods: 'GET'
    )]
    #[IsGranted('VIEW', subject: 'comment')]
    public function show(Comment $comment): Response
    {
        return $this->render('comment/show.html.twig', ['comment' => $comment]);
    }

    /**
     * Create action.
     *
     * @param Request $request HTTP request
     * @param Photo   $photo   Photo entity
     *
     * @return Response HTTP response
     */
    #[Route('/create/{id}', name: 'comment_create', methods: 'GET|POST', )]
    public function create(Request $request, Photo $photo): Response
    {
        $comment = new Comment();
        $comment->setAuthor($this->getUser());
        $comment->setPhoto($photo);
        $form = $this->createForm(
            CommentType::class,
            $comment,
            ['action' => $this->generateUrl('comment_create', ['id' => $photo->getId()])]
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->commentService->save($comment);

            $this->addFlash(
                'success',
                $this->translator->trans('message.created_successfully')
            );

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('comment/create.html.twig', ['form' => $form->createView()]);
    }

    /**
     * Edit action.
     *
     * @param Request $request HTTP request
     * @param Comment $comment Comment entity
     *
     * @return Response HTTP response
     */
    #[Route('/{id}/edit', name: 'comment_edit', requirements: ['id' => '[1-9]\d*'], methods: 'GET|PUT')]
    #[IsGranted('EDIT', subject: 'comment')]
    #[IsGranted('MANAGE')]
    public function edit(Request $request, Comment $comment): Response
    {
        $form = $this->createForm(
            CommentType::class,
            $comment,
            [
                'method' => 'PUT',
                'action' => $this->generateUrl('comment_edit', ['id' => $comment->getId()]),
            ]
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->commentService->save($comment);

            $this->addFlash(
                'success',
                $this->translator->trans('message.edited_successfully')
            );

            return $this->redirectToRoute('comment_index');
        }

        return $this->render(
            'comment/edit.html.twig',
            [
                'form' => $form->createView(),
                'Comment' => $comment,
            ]
        );
    }

    /**
     * Delete action.
     *
     * @param Request $request HTTP request
     * @param Comment $comment Comment entity
     *
     * @return Response HTTP response
     */
    #[Route('/{id}/delete', name: 'comment_delete', requirements: ['id' => '[1-9]\d*'], methods: 'GET|DELETE')]
    #[IsGranted('DELETE', subject: 'comment')]
    public function delete(Request $request, Comment $comment): Response
    {
        $form = $this->createForm(
            FormType::class,
            $comment,
            [
                'method' => 'DELETE',
                'action' => $this->generateUrl('comment_delete', ['id' => $comment->getId()]),
            ]
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->commentService->delete($comment);

            $this->addFlash(
                'success',
                $this->translator->trans('message.deleted_successfully')
            );

            return $this->redirectToRoute('comment_index');
        }

        return $this->render(
            'comment/delete.html.twig',
            [
                'form' => $form->createView(),
                'comment' => $comment,
            ]
        );
    }
}

templates/comment/create.html.twig
{% include 'default/_form.html.twig' with {
    page_title: 'make_a_comment'|trans,
    form: form,
    submit_label: 'save_index'|trans,
    back_to_list_path: 'comment_index',
} %}

templates/comment/delete.html.twig
{% include 'default/_form.html.twig' with {
    page_title: 'Delete_a_comment'|trans({'%id%': comment.id|default('')}),
    form: form,
    submit_label: 'do_delete'|trans,
    back_to_list_path: 'comment_index',
} %}

templates/comment/edit.html.twig
{% include 'default/_form.html.twig' with {
    page_title: 'Edit_a_comment'|trans({'%id%': comment.id|default('')}),
    form: form,
    submit_label: 'save_index'|trans,
    back_to_list_path: 'comment_index',
} %}

templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'photos_comments'|trans }}
{% endblock %}

{% block body %}

    <h1>{{ 'photos_comments'|trans }}</h1>
    {% if pagination is defined and pagination.items|length %}

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Id'|trans, 'comment.id') }}</th>
                <th>{{ 'Photo title'|trans }}</th>
                <th>{{ 'Author'|trans }}</th>
                <th>{{ 'Content'|trans }}</th>
                <th>{{ 'Actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for comment in pagination.items %}
                <tr>
                    <td>{{ comment.id }}</td>
                    <td>{{ comment.photo.title }}</td>
                    <td>{{ comment.author.username }}</td>
                    <td>{{ comment.content }}</td>
                    <td>
                        {% if is_granted('VIEW', comment) %}
                            <a href="{{ url('comment_show', {id: comment.id}) }}" title="{{ 'action.show'|trans }}" class="btn">
                                {{ 'show_me'|trans }}
                            </a>
                        {% endif %}
                        {% if is_granted('EDIT', comment) %}
                            <a href="{{ url('comment_edit', {id: comment.id}) }}" title="{{ 'action.edit'|trans }}" class="btn">
                                {{ 'do_edit'|trans }}
                            </a>
                        {% endif %}
                        {% if is_granted('DELETE', comment) %}
                            <a href="{{ url('comment_delete', {id: comment.id}) }}" title="{{ 'action.delete'|trans }}" class="btn">
                                {{ 'do_delete'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

    {% else %}
        <p>
            {{ 'message.empty_list'|trans }}
        </p>
    {% endif %}
{% endblock %}

templates/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'comment_details'|trans({'%id%': comment.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'comment_details'|trans({'%id%': comment.id|default('')}) }}</h1>
    {% if comment is defined and comment|length %}
        <dl class="dl-horizontal">
            <dt>{{ 'Id'|trans }}</dt>
            <dd>{{ comment.id }}</dd>
            <dt>{{ 'Photo title'|trans }}</dt>
            <dd>{{ comment.photo.title }}</dd>
            <dt>{{ 'Author'|trans }}</dt>
            <dd>{{ comment.author.username }}</dd>
            <dt>{{ 'Content'|trans }}</dt>
            <dd>{{  comment.content }}</dd>
        </dl>
        <p>
            <a href="{{ url('comment_index') }}" title="{{ 'action.back_to_comments'|trans }}" class="{{ 'btn btn-light' }}">
                {{ 'action.back_to_comments'|trans }}
            </a>
        </p>
    {% else %}
        <p>
            {{ 'message.comment_not_found'|trans }}
        </p>
    {% endif %}
{% endblock %}